import assert from 'node:assert/strict';
import {assignService} from '../static/shared_service.mjs';
import {simulateBranch,BRANCH_DEFAULTS} from '../static/branch/model.mjs';
import {nodeState} from '../static/branch/node_state.mjs';
import {liveMetrics} from '../static/branch/live_metrics.mjs';
const jobs=[{id:0,arrival:0,work:4},{id:1,arrival:1,work:3},{id:2,arrival:2,work:1}];
assert.deepEqual([...assignService(jobs,1).values()].map(x=>x.start),[0,4,7]);
assert.deepEqual([...assignService(jobs,2).values()].map(x=>x.start),[0,1,4]);
assert.equal(assignService([...jobs,{id:3,arrival:2.5,work:0}],1).get(3).start,2.5);
assert.throws(()=>assignService(jobs,0));
const one=simulateBranch(BRANCH_DEFAULTS),off=simulateBranch({...BRANCH_DEFAULTS,serviceEnabledC:0});
for(const r of off.rows)assert.equal(r.serviceQueueC,0);
assert.equal(one.rows[1].serviceStartC,19);assert.equal(one.rows[2].serviceStartC,21);
assert.equal(one.rows[3].serviceStartC,one.rows[2].serviceEndC);
assert.ok(one.rows[3].departC>off.rows[3].departC);
for(const a of one.rows)for(const b of one.rows)if(a.id!==b.id&&a.workC>0&&b.workC>0)assert.ok(a.serviceEndC<=b.serviceStartC||b.serviceEndC<=a.serviceStartC);
assert.ok(nodeState(one,'C',20).present.some(x=>x.id===2&&x.state==='设备排队'));
const before=liveMetrics(one.economics,20);assert.equal(before.stage,'C 设备排队');assert.equal(before.goods[1].delivered,0);
const many=simulateBranch({...BRANCH_DEFAULTS,serviceServersC:6});assert.ok(many.rows.every(r=>r.serviceQueueC===0));
console.log('Hand FCFS, parallel servers, zero work, cross-branch coupling, nonoverlap, queue state and delayed delivery passed');
