import assert from 'node:assert/strict';
import {simulateFull} from '../static/branch/full_model.mjs';
import {eventSchedule} from '../static/branch/event_network.mjs';
import {networkLedger} from '../static/branch/network_economics.mjs';
import {JOINT_DEFAULTS} from '../static/branch/joint.mjs';
import {runOperations,options,disruptionCalendar,hourlyMetrics,flightTrace} from '../static/branch/operations.mjs';
import {generateDemand} from '../static/branch/random_demand.mjs';
const base={...simulateFull({}).p,ac:1,fullCD:1,fullCE:1,fullDB:1,fullEB:1,speed:60,battery:10,energyReserve:0,k0:.02,kLoad:0,loiterRate:.001,handlingEnergyC:0,handlingEnergyD:0,serviceEnabledC:1,serviceServersC:1,sharedC:0,sharedD:0,winchEnabled:0,target:-1,groundStandby:0,departuresC:[4,8,65],departuresCE:[],departuresD:[10,70],departuresEB:[],batchMax:10,batchReserve:0,joinBuffer:0};
const job={id:0,origin:'A',branch:'D',destination:'B',created:0,weight:1,dropC:0,loadC:0,loadHub:0,workC:2,workHub:0,cargoType:'普通',feeFactor:1,dispatchDeadline:90};
const o={...JOINT_DEFAULTS,deadline:90,surfaceModel:0},p={...base,fullJobs:[job]};
const normal=eventSchedule(p,0,0,o),weather=eventSchedule(p,0,0,{...o,disruptions:[{type:'weather',station:'all',start:3,end:6}]});
assert.equal(normal.rows[0].departC,4);assert.equal(weather.rows[0].departC,8);assert.equal(weather.batches.find(b=>b.time===4).cancelled,true);assert.ok(flightTrace(weather,weather.rows[0]).missed.some(m=>m.reason==='天气停航'));
const fault=eventSchedule({...p,fullJobs:[job,{...job,id:1}]},0,0,{...o,disruptions:[{type:'device',station:'C',start:2,end:6}]});assert.equal(fault.rows[0].serviceEndC,3);assert.equal(fault.rows[1].serviceStartC,6);
const crossing=eventSchedule({...p,departuresC:[65],departuresD:[70]},0,0,o),hours=hourlyMetrics(crossing,{});assert.equal(hours[0].atC,1);assert.equal(hours[1].completed,1);
const empty=eventSchedule({...p,fullJobs:[]},0,0,{...o,disruptions:[{type:'device',station:'C',start:2,end:6}],faultRepairCost:5}),ledger=networkLedger(p,empty,{...o,disruptions:[{type:'device',station:'C',start:2,end:6}],faultRepairCost:5});assert.equal(ledger.totals.maintenance,5);assert.ok(ledger.net<0);
assert.deepEqual(disruptionCalendar(7,options()),disruptionCalendar(7,options()));assert.deepEqual(disruptionCalendar(7,options({weatherRate:0,faultRate:0})),[]);assert.throws(()=>options({padCount:1.5}));assert.throws(()=>options({weatherRate:2}));
const demand=generateDemand({...base,demandMode:1,maxJobs:2048,sourceEnd:1440,hourlyDemandProfile:Array.from({length:24},(_,h)=>h===8?1:0),sourceRateA:.2,sourceRateCD:0,sourceRateCE:0,sourceRateD:0,sourceRateE:0});assert.ok(demand.length>0);assert.ok(demand.every(j=>j.created>=480&&j.created<=540));
const r=runOperations(simulateFull({}),{runs:2,weatherRate:0,faultRate:0});assert.equal(r.exploration.length,64);assert.equal(new Set([...r.seeds,...r.reviewSeeds]).size,4);assert.ok(Math.abs(r.gain.mean-(r.review.meanNet-r.reference.meanNet))<1e-8);assert.deepEqual(r.review.trials.map(t=>t.net),r.stress.trials.map(t=>t.net));assert.ok(r.review.trials.every(t=>t.hours.length===24));assert.ok(r.exploration.every(x=>x.trials.every(t=>r.seeds.includes(t.seed))));if(!r.choice)assert.equal(r.recommended,false);
console.log('PASS 24h profile, cross-hour backlog, weather cancellation, nonpreemptive device outage, repair/idle costs, paired independent replication and no false recommendation');
