import assert from 'node:assert/strict';
import {FOUR_DEFAULTS as p,evaluateFour,optimizeFour,scheduleFour,effectivePayload} from '../static/four_model.mjs';

const x=optimizeFour(p);
assert.ok(x.target.arrivalB!==null);
assert.ok(x.energy<=p.battery+1e-9);
const reserved=optimizeFour({...p,energyReserve:.2});
assert.ok(reserved.energy<=p.battery-.2+1e-9);
assert.ok(reserved.net<=x.net+1e-9);
assert.throws(()=>optimizeFour({...p,energyReserve:p.battery}),/备用电量/);
assert.ok(x.workC+p.joinBuffer<=x.target.waitC+1e-9);
assert.ok(x.workD+p.joinBuffer<=x.target.waitD+1e-9);
assert.ok(Math.abs(x.target.arrivalD-(x.target.departC+p.cd/p.speed*60))<1e-9);
assert.ok(x.net>=x.matched.net-1e-9);
assert.ok(x.p.q+Math.max(x.dC,x.lC,x.lD)<=effectivePayload(x.p)+1e-9);
assert.ok(Math.max(x.dC,x.lC,x.lD)<=p.winchCapacity+1e-9);
assert.throws(()=>optimizeFour({...p,db:70}),/总航程/);
const beyond=optimizeFour({...p,db:60,q:6,allowExtrapolation:1,battery:8});
assert.ok(beyond.target.arrivalB!==null);
const timed=evaluateFour({...p,winchTiming:1,battery:8},2,1,1);
assert.ok(timed.workC>0&&timed.drop>0);
assert.ok(timed.workC!==evaluateFour({...p,battery:8},2,1,1).workC);
assert.ok(Math.abs(x.direct.energy-p.direct*(p.k0+p.kLoad*p.q))<1e-9);
assert.ok(Math.abs(x.energy-(x.eAC+x.eCD+x.eDB+x.eWait+x.eHandle))<1e-9);
assert.equal(evaluateFour(p,p.bay+1,0,0),null);
assert.equal(evaluateFour({...p,battery:.01},0,0,0),null);
const normal=scheduleFour(p,0,0).rows[p.target];
const delayed=scheduleFour(p,10,0).rows[p.target];
assert.ok(delayed.departC>normal.departC);
assert.ok(delayed.arrivalD>normal.arrivalD);
const airspace=optimizeFour({...p,sharedC:1,airspaceC:3});
assert.ok(airspace.workC<=3+1e-9);
assert.throws(()=>optimizeFour({...p,arrivalsC:[1,2]}));
console.log('Four-station cargo, queue propagation, energy parity and constraints passed.');
